#!/usr/bin/env python3
import re
import sys
import csv
from collections import defaultdict
from datetime import datetime
ergfrg
LOG_PATTERN = re.compile(
    r'(?P<ip>\d{1,3}(?:\.\d{1,3}){3})\ssdfsfdgdfgdf+-\s+(?P<user>[^ ]+)\s+\[(?P<time>[^\]]+)\]\s+"(?P<method>GET|POST|PUT|DELETE|HEAD|OPTIONS)\s+(?P<uri>[^"]+)\s+HTTP/[0-9.]+"\s+(?P<status>\d{3})\s+(?P<size>\d+|-)'
)

SQL_KEYWORDS = ("UNION", "SELECT", "OR 1=1", "DROP", "INSERT", "UPDATE", "WHERE")

def parse_clf_line(line):
    m = LOG_PATTERN.search(line)
    if not m:
        return None
    d = m.groupdict()
    try:
        d['time'] = datetime.strptime(d['time'].split()[0], "%d/%b/%Y:%H:%M:%S")
    except Exception:
        pass
    return d

def is_suspicious_uri(uri):
    u = uri.upper()
    if len(u) > 200:
        return True
    for k in SQL_KEYWORDS:
        if k in u:
            return True
    return False

def main(logfile, out_csv="parsed_events.csv", ioc_file="iocs.txt"):
    stats = defaultdict(int)
    suspicious_events = []
    suspect_ips = set()
    suspect_uris = set()

    with open(logfile, "r", errors="ignore") as fh:
        for line in fh:
            entry = parse_clf_line(line)
            if not entry:
                continue
            ip = entry['ip']
            uri = entry['uri']
            status = entry['status']
            method = entry['method']
            stats[ip] += 1

            if is_suspicious_uri(uri):
                suspicious_events.append((entry['time'], ip, method, uri, status))
                suspect_ips.add(ip)
                suspect_uris.add(uri)

            if method == "POST" and "/login" in uri.lower():
                stats[f"login:{ip}"] += 1

    with open(out_csv, "w", newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["time", "src_ip", "method", "uri", "status"])
        for ev in sorted(suspicious_events):
            writer.writerow([ev[0], ev[1], ev[2], ev[3], ev[4]])

    with open(ioc_file, "w") as f:
        f.write("# iocs generated by parse_logs.py\n")
        for ip in sorted(suspect_ips):
            f.write(f"ip:{ip}\n")
        for uri in sorted(suspect_uris):
            f.write(f"uri:{uri}\n")

    brute_force_candidates = []
    for key, val in stats.items():
        if key.startswith("login:") and val > 10:
            brute_force_candidates.append((key.split(":",1)[1], val))

    if brute_force_candidates:
        with open("bruteforce_summary.txt", "w") as bf:
            for ip, count in brute_force_candidates:
                bf.write(f"{ip} failed_login_attempts:{count}\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: parse_logs.py <access.log> [out.csv] [iocs.txt]")
        sys.exit(1)
    logfile = sys.argv[1]
    out_csv = sys.argv[2] if len(sys.argv) > 2 else "parsed_events.csv"
    ioc_file = sys.argv[3] if len(sys.argv) > 3 else "iocs.txt"
    main(logfile, out_csv, ioc_file)
